### ISSUE TITLE
Doesn't work with Firefox 57+ (new extension technology)

### ISSUE THREAD

**Issue by condab** [carlin-q-scott/browser-media-keys#153] opened 2017-10-28 00:45 UTC
Apologies if I'm posting an obvious problem here, or if the developers are already working on the new version. Just thought I would bring this up as I just noticed that the extension was not working just today. This is explained here: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct

**Comment by AlmightyFloppyFish** [comment] 2017-10-28 15:31
I think many, if not most Firefox users have already switched to the 57 beta since It's absolutely amazing. So making this compatible should be priority

**Comment by jerome-tgl** [comment] 2017-10-30 09:23
Duplicate of #150

**Comment by svnpenn** [comment] 2017-11-08 15:22
https://github.com/andymckay/arewewebextensionsyet.com/issues/20

**Comment by svnpenn** [comment] 2017-11-08 15:24
https://github.com/andymckay/arewewebextensionsyet.com/issues/21

**Comment by svnpenn** [comment] 2017-11-23 16:54
https://github.com/carlin-q-scott/browser-media-keys/issues/155

**Comment by MaxValue** [comment] 2018-03-12 13:32
Please close this issue @condab, as it is a duplicate of #150.

**Comment by cup** [comment] 2018-08-23 17:53
https://github.com/carlin-q-scott/browser-media-keys/issues/158

**Closed** 2018-10-08 03:54 UTC

**Comment by cup** [comment] 2018-10-08 13:43
Note that Version 2.0.0 of this addon does not work with Firefox 56. Make sure
to turn Automatic Updates off.
