### ISSUE TITLE
Play/Pause not working in windows 7 Enterprise

### ISSUE THREAD

**Issue by chimicus** [carlin-q-scott/browser-media-keys#19] opened 2015-09-18 12:41 UTC
I'm trying to use the extension on Windows 7 Enterprise, on a Thinkpad with external Microsoft comfort curve keyboard v1.0 and I cannot get youtube to pause when hitting Play / pause. I tried the key with widows media player to confirm the key is working and... it is working. 
I restarted firefox, reloaded youtube, focused on the page, focused on different tabs, on different applications but nothing at all.
Any information I can provide you with just let me know.

**Comment by carlin-q-scott** [comment] 2015-09-21 23:22
Thanks for the bug report. I'm able to reproduce this on Windows 7 Premium with a Logitech k260.

**Comment by chimicus** [comment] 2015-09-22 06:35
Thank you for the quick answer, can I help in any way?
Il 22/set/2015 00:22, "Carlin Scott" <notifications@github.com> ha scritto:

**Comment by carlin-q-scott** [comment] 2015-09-24 05:49
Not at this moment unless you're a js developer. I have to rework some of
the add-on code just to see what's breaking.

**Comment by chimicus** [comment] 2015-09-24 08:04
I am a developer :)

If you need a second view on the code or ideas to implement an algorithm...
or unit tests ;)

Emiliano

2015-09-24 6:49 GMT+01:00 Carlin Scott <notifications@github.com>:

> Not at this moment unless you're a js developer. I have to rework some of
> the add-on code just to see what's breaking.
>
> On Mon, Sep 21, 2015, 23:35 chimicus <notifications@github.com> wrote:
>
> > Thank you for the quick answer, can I help in any way?
> > Il 22/set/2015 00:22, "Carlin Scott" <notifications@github.com> ha
> > scritto:
> >
> > > Thanks for the bug report. I'm able to reproduce this on Windows 7
> > Premium
> > > with a Logitech k260.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/carlin-q-scott/browser-media-keys/issues/19#issuecomment-142136040
> > >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/carlin-q-scott/browser-media-keys/issues/19#issuecomment-142194326
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carlin-q-scott/browser-media-keys/issues/19#issuecomment-142818258>
> .
>



-- 
Emiliano Testa
Cisco software Engineer
Mobile Phone: +44 (0)7512 468 305
Work Phone: +44 (0)2380301660
email: testa.emiliano@gmail.com

«bit happens». Terminator 2

"Il debole non può perdonare, il perdono è prerogativa del forte" Mahatma
Ghandi

"Nessuno ha amore <http://it.wikiquote.org/wiki/Amore> più grande di colui
che sa rispettare la libertà
<http://it.wikiquote.org/wiki/Libert%C3%A0> dell'altro."
Simone Weil

"Il paesaggio della sua poesia era ancora il deserto..." Salman Rushdie,
Versi satanici

"siamo tutti omosessuali, si puó guarire anche dalla normalitá" Radici nel
cemento

**Comment by carlin-q-scott** [comment] 2015-09-25 02:09
Awesome, I would really appreciate the help! 

My first run through the FIrefox add-on debugger found that the [https://github.com/carlin-q-scott/browser-media-keys/blob/master/data/windowsHotkeys.js](windowsHotkeys.js) isn't responding to the attach message emitted by [https://github.com/carlin-q-scott/browser-media-keys/blob/master/lib/hotkeyManager.js#L24](hotkeyManager.js) which probably means it's stuck registering the hotkeys. In order to debug the windowsHotkeys.js it needs to be converted to work like the linuxHotkeys.js because ChromeWorkers cannot be debugged apparently.

Do you have any interest in making that modification and debugging the file to find where it's stuck and maybe why?

**Comment by chimicus** [comment] 2015-09-25 08:12
Hi Carlin,

I'm more than happy to help, but please do consider that I'll be doing in
my spare time, I'll work on this during the weekends and the evenings when
nothing else is on my list :)

If that's good for you, it's good for me

Emiliano

2015-09-25 3:09 GMT+01:00 Carlin Scott <notifications@github.com>:

> Awesome, I would really appreciate the help!
>
> My first run through the FIrefox add-on debugger found that the
> https://github.com/carlin-q-scott/browser-media-keys/blob/master/data/windowsHotkeys.js
> <http://windowsHotkeys.js> isn't responding to the attach message emitted
> by
> https://github.com/carlin-q-scott/browser-media-keys/blob/master/lib/hotkeyManager.js#L24
> <http://hotkeyManager.js> which probably means it's stuck registering the
> hotkeys. In order to debug the windowsHotkeys.js it needs to be converted
> to work like the linuxHotkeys.js because ChromeWorkers cannot be debugged
> apparently.
>
> Do you have any interest in making that modification and debugging the
> file to find where it's stuck and maybe why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carlin-q-scott/browser-media-keys/issues/19#issuecomment-143102787>
> .
>



-- 
Emiliano Testa
Cisco software Engineer
Mobile Phone: +44 (0)7512 468 305
Work Phone: +44 (0)2380301660
email: testa.emiliano@gmail.com

«bit happens». Terminator 2

"Il debole non può perdonare, il perdono è prerogativa del forte" Mahatma
Ghandi

"Nessuno ha amore <http://it.wikiquote.org/wiki/Amore> più grande di colui
che sa rispettare la libertà
<http://it.wikiquote.org/wiki/Libert%C3%A0> dell'altro."
Simone Weil

"Il paesaggio della sua poesia era ancora il deserto..." Salman Rushdie,
Versi satanici

"siamo tutti omosessuali, si puó guarire anche dalla normalitá" Radici nel
cemento

**Comment by chimicus** [comment] 2015-09-28 10:48
apparently the problem is the use of PeekMessage(). It never enters the
while().

Is there a particular reason for choosing this interface?
I guess you want to use web workers to listen to events happening even if
focus is not on the main window.

My skills are more towards embedded devices and I know very little about
Windows APIs but, if you give me enough time, I'll come back to you with
something working in my environment (I'll let you test is on different
ones) :)

Regards

Emiliano

2015-09-25 9:12 GMT+01:00 Emiliano Testa <testa.emiliano@gmail.com>:

> Hi Carlin,
>
> I'm more than happy to help, but please do consider that I'll be doing in
> my spare time, I'll work on this during the weekends and the evenings when
> nothing else is on my list :)
>
> If that's good for you, it's good for me
>
> Emiliano
>
> 2015-09-25 3:09 GMT+01:00 Carlin Scott <notifications@github.com>:
>
>> Awesome, I would really appreciate the help!
>>
>> My first run through the FIrefox add-on debugger found that the
>> https://github.com/carlin-q-scott/browser-media-keys/blob/master/data/windowsHotkeys.js
>> <http://windowsHotkeys.js> isn't responding to the attach message
>> emitted by
>> https://github.com/carlin-q-scott/browser-media-keys/blob/master/lib/hotkeyManager.js#L24
>> <http://hotkeyManager.js> which probably means it's stuck registering
>> the hotkeys. In order to debug the windowsHotkeys.js it needs to be
>> converted to work like the linuxHotkeys.js because ChromeWorkers cannot be
>> debugged apparently.
>>
>> Do you have any interest in making that modification and debugging the
>> file to find where it's stuck and maybe why?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/carlin-q-scott/browser-media-keys/issues/19#issuecomment-143102787>
>> .
>>
>
>
>
> --
> Emiliano Testa
> Cisco software Engineer
> Mobile Phone: +44 (0)7512 468 305
> Work Phone: +44 (0)2380301660
> email: testa.emiliano@gmail.com
>
> «bit happens». Terminator 2
>
> "Il debole non può perdonare, il perdono è prerogativa del forte" Mahatma
> Ghandi
>
> "Nessuno ha amore <http://it.wikiquote.org/wiki/Amore> più grande di
> colui che sa rispettare la libertà
> <http://it.wikiquote.org/wiki/Libert%C3%A0> dell'altro." Simone Weil
>
> "Il paesaggio della sua poesia era ancora il deserto..." Salman Rushdie,
> Versi satanici
>
> "siamo tutti omosessuali, si puó guarire anche dalla normalitá" Radici nel
> cemento
>



-- 
Emiliano Testa
Cisco software Engineer
Mobile Phone: +44 (0)7512 468 305
Work Phone: +44 (0)2380301660
email: testa.emiliano@gmail.com

«bit happens». Terminator 2

"Il debole non può perdonare, il perdono è prerogativa del forte" Mahatma
Ghandi

"Nessuno ha amore <http://it.wikiquote.org/wiki/Amore> più grande di colui
che sa rispettare la libertà
<http://it.wikiquote.org/wiki/Libert%C3%A0> dell'altro."
Simone Weil

"Il paesaggio della sua poesia era ancora il deserto..." Salman Rushdie,
Versi satanici

"siamo tutti omosessuali, si puó guarire anche dalla normalitá" Radici nel
cemento

**Comment by carlin-q-scott** [comment] 2015-09-28 22:54
It's fine to work on this in your free time; that's all I'm doing anyways.

The Windows API provides two means of accessing the media key events (in order to support unfocused key events) and this is the only one that doesn't require intercepting OS events destined to the main Firefox window.

PeekMessage() should be doing what it says and simply peeking at the windows event message queue. Most likely there's an issue with calling that method, as it is defined by the ctypes code, on the affected machines. Unless you want to spend a bunch of time learning ctypes and WinAPI I can take over from here.

**Comment by chimicus** [comment] 2015-09-29 08:16
I can keep on working on it,
I think the PeekMessage() is also blocking messages FROM the Web Worker: if
I comment the line out I do see messages coming, if I don't then the
messages do not come.
I have found a package for node.js we could use to capture hot keys events:
hott. I didn't try it but it looks promising.

I can continue the investigation, I quite like working on something
different from time to time, I don't want to take decision though as I'm
not the "owner". So I'll wait for you to decide what to do next.

If you want to keep me updated and you want me to continue what I'm doing
then let me know :)

Best Regards

Emiliano

2015-09-28 23:54 GMT+01:00 Carlin Scott <notifications@github.com>:

> It's fine to work on this in your free time; that's all I'm doing anyways.
>
> The Windows API provides two means of accessing the media key events (in
> order to support unfocused key events) and this is the only one that
> doesn't require intercepting OS events destined to the main Firefox window.
>
> PeekMessage() should be doing what it says and simply peeking at the
> windows event message queue. Most likely there's an issue with calling that
> method, as it is defined by the ctypes code, on the affected machines.
> Unless you want to spend a bunch of time learning ctypes and WinAPI I can
> take over from here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carlin-q-scott/browser-media-keys/issues/19#issuecomment-143896072>
> .
>



-- 
Emiliano Testa
Cisco software Engineer
Mobile Phone: +44 (0)7512 468 305
Work Phone: +44 (0)2380301660
email: testa.emiliano@gmail.com

«bit happens». Terminator 2

"Il debole non può perdonare, il perdono è prerogativa del forte" Mahatma
Ghandi

"Nessuno ha amore <http://it.wikiquote.org/wiki/Amore> più grande di colui
che sa rispettare la libertà
<http://it.wikiquote.org/wiki/Libert%C3%A0> dell'altro."
Simone Weil

"Il paesaggio della sua poesia era ancora il deserto..." Salman Rushdie,
Versi satanici

"siamo tutti omosessuali, si puó guarire anche dalla normalitá" Radici nel
cemento

**Comment by carlin-q-scott** [comment] 2015-10-03 18:14
So I found out that on the computer I have which is experiencing a similar issue, that the cause of it was Logitech SetPoint. It intercepts and handles the media keys and then sends them on to media players that it knows about. Simply closing the application fixed the issue for me. Maybe you have a similar application installed for your keyboard?

**Comment by chimicus** [comment] 2015-10-04 11:32
Yup,
that worked!! My problem was the presence of microsoft mouse and keyboard
center. Removed it and suddenly it started working.

I didn't know I had it installed :(

Cheers!!!!

Emiliano (very happy for the great improvement :) )

2015-10-03 19:14 GMT+01:00 Carlin Scott <notifications@github.com>:

> So I found out that on the computer I have which is experiencing a similar
> issue, that the cause of it was Logitech SetPoint. It intercepts and
> handles the media keys and then sends them on to media players that it
> knows about. Simply closing the application fixed the issue for me. Maybe
> you have a similar application installed for your keyboard?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carlin-q-scott/browser-media-keys/issues/19#issuecomment-145273878>
> .
>



-- 
Emiliano Testa
Cisco software Engineer
Mobile Phone: +44 (0)7512 468 305
Work Phone: +44 (0)2380301660
email: testa.emiliano@gmail.com

«bit happens». Terminator 2

"Il debole non può perdonare, il perdono è prerogativa del forte" Mahatma
Ghandi

"Nessuno ha amore <http://it.wikiquote.org/wiki/Amore> più grande di colui
che sa rispettare la libertà
<http://it.wikiquote.org/wiki/Libert%C3%A0> dell'altro."
Simone Weil

"Il paesaggio della sua poesia era ancora il deserto..." Salman Rushdie,
Versi satanici

"siamo tutti omosessuali, si puó guarire anche dalla normalitá" Radici nel
cemento

**Comment by carlin-q-scott** [comment] 2015-10-05 15:07
Awesome! I'm glad that fixed it for you!

**Closed by carlin-q-scott** 2015-10-05 15:07 UTC
Labels: bug
