### ISSUE TITLE
Fails when localhost is open in other tab

### ISSUE THREAD

**Issue by savelbr** [carlin-q-scott/browser-media-keys#47] opened 2016-03-04 11:47 UTC
This is an excellent addon. It works perfectly for me, except in the following scenario:

1) Play youtube/spotify/other with any number of other "normal" tabs open => works perfectly
2) Open new tab with a page/app served from localhost (e.g. http://localhost:8080) => stops working
3) Navigate to any other tab without closing the localhost tab => still broken
4) Close the localhost tab => still broken
5) Activate spotify/youtube/other tab => works perfectly again
6) Navigate to any other "normal" tab => still works
7) Open the same locally served page/app, but now from 127.0.0.1 (e.g. http://127.0.0.1:8080) => still works

So their seems to be a bug that breaks things specifically with localhost tabs, but not on 127.0.0.1 tabs. I had a quick look at the code, but couldn't find any obvious causes.

I'm running the addon in Firefox 44.0.2 on Ubuntu 15.10

**Comment by carlin-q-scott** [comment] 2016-03-24 05:42
I believe Jamstash matches against localhost. Which version of the add-on are you using? I've changed the site matching logic for jamstash so that might be the cause.

**Comment by savelbr** [comment] 2016-04-02 12:28
I'm using v0.6.6

**Comment by carlin-q-scott** [comment] 2016-05-06 03:06
I believe this was resolved by 20c1d49a3b5af94863b0e194d741a95aebeb409d which was in the currently recalled v0.7.0. I'll try to push out v0.7.1 soon.

**Closed by carlin-q-scott** 2016-05-06 03:06 UTC
Labels: bug
